### ISSUE TITLE
Set max limit number

### ISSUE THREAD

**Issue by tnanhkhoa** [momokang/slotmachine#1]
Hi
I like your work. 
I have a question: how can i set max limit of the number before randomly spinning?
For example: i set the max limit is 300, and then the result is less or equal than 300, not more than 300 (305, 666, ...)
Thank you.

**Comment by momokang** [comment]
Hi, checkout the example 2 at https://momokang.github.io/slotmachine/
You can set a random number at your js, split it as array and use example 2, eg:

`// 1 -> 300`
`var rand = "" + Math.floor(Math.random() * 300) + 1;`
`var numbers = rand.split("");`
`$('#example2 ul').playSpin({`
    `endNum: numbers,`
`});`

I didn't try the above script but you should get the idea.

**Comment by tnanhkhoa** [comment]
Thank you so much. I'll try.

**Comment by tnanhkhoa** [comment]
Excuse me, i have a question about your method: what's inside "" in var rand = "" + Math.floor(Math.random() * 300) + 1; and var numbers = rand.split("");
Thank you.

**Comment by momokang** [comment]
This is random number from 1 to 300
