### ISSUE TITLE
fetching number based on amount of data

### ISSUE THREAD

**Issue by peterwira** [momokang/slotmachine#2]
hi, thank you for the code.

I want to get the numbers from the server, and split it into each part (in this case, I used str_split() ).

how can I fetch the divided numbers via ajax, and set the slot machine to display the exact numbers that I random?

here below I attach my current project. thank you again.
[slotmachine.zip](https://github.com/momokang/slotmachine/files/4762359/slotmachine.zip)

**Comment by momokang** [comment]
You can either ajax few times, to get each number once per time, or combine the numbers and ajax once.

**Comment by peterwira** [comment]
if I ajax it multiple times, it will generate different random numbers. I want it so that when the slot starts to stop it will display the exact numbers after the randomization. I can't echo the divided number by PHP, so I'm currently stuck..

**Comment by momokang** [comment]
Then you should ajax once, get the combined number, with PHP you can simply combine $number with `$number = $num1 . $num2;`

**Comment by peterwira** [comment]
I see, but how do I fetch the numbers if I randomize them after I clicked "start"? It doesn't seem to be showing the numbers if I tried to echo them..

**Comment by momokang** [comment]
Do your ajax is working? For starting don't try to randomize, you can try hardcode in your PHP, for example 123, your ajax is working when you can get 123, then you can start develop randomize in PHP.

**Comment by peterwira** [comment]
yes it's working (here's the screenshot)
![2020-06-15 (1)](https://user-images.githubusercontent.com/66762382/84612229-300d9c00-aeea-11ea-84f0-5a3fcdeb9382.png)

I have to put "include_once" to get the hardcode number, but the numbers won't stop at the endNum I declared on the code (on Source panel)

**Comment by momokang** [comment]
Oh no, this is not ajax, this is hardcoded at HTML javascript, if you are using include_once by refresh in PHP, you can write something like this:
`endNum: <?php echo $num1; ?>`

**Comment by peterwira** [comment]
I think you meant it like this (in the screenshot)
![2020-06-15 (5)](https://user-images.githubusercontent.com/66762382/84612639-6e578b00-aeeb-11ea-8c8a-907861fa73cf.png)

the result was the exact same result on the previous screenshot. and it will always display 012 on the slotmachine.

*edited
I moved the include_once code into the ajax

**Comment by momokang** [comment]
Based on your code, you are not using a proper ajax, because you hardcoded `$a`, `$b`, and `$c` without getting data from ajax after `done`, you need to understand what is ajax: https://api.jquery.com/deferred.done/

**Comment by momokang** [comment]
Alternatively, you directly refresh the page, randomize at php level, and show `$a`, `$b`, `$c` instead, you can try change `$a = 3` at top of your code, it will change accordingly.

**Comment by peterwira** [comment]
okay then, I'll try it.

one more thing, is it possible when I click on the stop button the machine will immediately stop spinning without animation?

**Comment by momokang** [comment]
Unfortunately, it didn't support stop spinning without animation.

**Comment by peterwira** [comment]
I see..

I've done getting the data via ajax, and I'm currently wanting to show the numbers based on the example #2. But instead on stopping at the exact number, the machine stopped at -1 the number, and if the result number is 0, it will stop at random number. (the screenshot below)

![2020-06-15 16_38_54-Window](https://user-images.githubusercontent.com/66762382/84642487-bea00e80-af26-11ea-85fb-be4496321ca3.png)

is there any way I can display the same value as the obj that I console.log ??

**Comment by momokang** [comment]
Check your html number sequence

**Comment by peterwira** [comment]
oh I get it, thank you for that.

I read your code about if the `endNum = 0` it will randomize from 1 to liCount. How do I disable that so when it reached 0 it won't be erased??
![2020-06-16 09_40_20-Document](https://user-images.githubusercontent.com/66762382/84725733-7ed43800-afb5-11ea-9de9-0b0e51322d42.png)
