### ISSUE TITLE
Connect to Sql

### ISSUE THREAD

**Issue by iwansoya** [momokang/slotmachine#4]
Hi guys, sorry for asking, 

I want to make the spin wheel as a lucky prize system. Since I want to connect with SQL, how can i do it? Since there is AJAX method, but i dont understand actually how to do it.

**Comment by momokang** [comment]
Hi,

this is front-end javascript, you need to have back-end knowledge, example PHP or ASP.NET C#, and connect with your SQL.
Then return it with ajax
