### ISSUE TITLE
How to run spin foreach number from database?

### ISSUE THREAD

**Issue by BalaMurugan888** [momokang/slotmachine#7]
For now we can select winner limit, for example 2 winner limit and then start spin, so it will get 2 numbers from database exp: (12345, 64854), after get the numbers it will display in spinner slot, but the issue is it will only spin one time and get the first data only, the second data was not spinning and display. i did put the playspin function in foreach numbers, but its working for first data only. How to spin it for 2 or 3 numbers(ForEach).

HTML
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-8">
                            <div class="card">
                                <div class="card-header">Slot Machine</div>
                
                                <div class="card-body">
                                    @if (session('status'))
                                        <div class="alert alert-success" role="alert">
                                            {{ session('status') }}
                                        </div>
                                    @endif
                
                                    <p>Select Winner Limit & Click Start To Start Lucky Draw Session</p>

                                        
                                        <label for="winner_limit">Winner Limit<span style="color:red;">*</span></label>
                                        <select name="winner_limit" class="form-control" id="winner_limit" required=''>
                                            <option selected>Select Limit</option>
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                        </select>
                                       
                                      <div class="panel panel-primary mt-3">
                                        <div class="panel-heading"></div>
                                        <div class="panel-body">
                                            <div class="well">       
                                            </div>
                                            <div class="slotwrapper" id="example1" style="animation-iteration-count: infinite;">
                                                <ul id="first">
                                                    <li>0</li>
                                                    <li>1</li>
                                                    <li>2</li>
                                                    <li>3</li>
                                                    <li>4</li>
                                                    <li>5</li>
                                                    <li>6</li>
                                                    <li class="text-danger">7</li>
                                                    <li>8</li>
                                                    <li>9</li>

                                                </ul>
                                                <ul id="second">
                                                    <li>0</li>
                                                    <li>1</li>
                                                    <li>2</li>
                                                    <li>3</li>
                                                    <li>4</li>
                                                    <li>5</li>
                                                    <li>6</li>
                                                    <li class="text-danger">7</li>
                                                    <li>8</li>
                                                    <li>9</li>
                                                </ul>
                                                <ul id="third">
                                                    <li>0</li>
                                                    <li>1</li>
                                                    <li>2</li>
                                                    <li>3</li>
                                                    <li>4</li>
                                                    <li>5</li>
                                                    <li>6</li>
                                                    <li class="text-danger">7</li>
                                                    <li>8</li>
                                                    <li>9</li>
                                                </ul>
                                                <ul id="fourth">
                                                    <li>0</li>
                                                    <li>1</li>
                                                    <li>2</li>
                                                    <li>3</li>
                                                    <li>4</li>
                                                    <li>5</li>
                                                    <li>6</li>
                                                    <li class="text-danger">7</li>
                                                    <li>8</li>
                                                    <li>9</li>
                                                </ul>
                                                <ul id="fifth">
                                                    <li>0</li>
                                                    <li>1</li>
                                                    <li>2</li>
                                                    <li>3</li>
                                                    <li>4</li>
                                                    <li>5</li>
                                                    <li>6</li>
                                                    <li class="text-danger">7</li>
                                                    <li>8</li>
                                                    <li>9</li>
                                                </ul>
                                            </div>
                                            <div>
                                                <button type="button" class="btn btn-success btn-lg" id="btn-example1">Start Spin!</button>
                                            </div>
                                        </div>
                                    </div>

                                    <input type="text" name="title" id="title">

                                    
                                    
                                </div>
                            </div>
                            
                        </div>
                        <div class="col-md-4">
                            <div class="card">
                                <div class="card-header">{{ __('Winner Panel') }}</div>
                                <div class="card-body">
                                    <div id ="displayMessage"> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

//script

  $('#btn-example1').click(function() {
        var sound = new Audio('ringtones/spinning.mp3');
        var ding = new Audio('ringtones/ding.wav');
        // Loop of playing sound
        sound.addEventListener('ended', function() {
            this.currentTime = 0;
            this.play();
        }, false);

        $('.winnerpanel').remove();

        if ($('#winner_limit').val() === "" || $('#winner_limit').val() === "Select Limit" ){
            alert('Please Select A Winner Limit');
        }
        // console.log($('#winner_limit').val());

        $winner_limit_value = $("#winner_limit").val();

        $.ajax({
                    url: '{{url('/')}}/getTickets/' + $winner_limit_value,
                    success: function (data) {

                       
                            $.each(data, function(i, ticket) {
                                if(ticket.ticket_code === 'Tickets Is Empty Please Enter Tickets Before Play Lucky Draw'){

                                    $("#displayMessage").append("<div class='winnerpanel' style='color:red;' id='winnerpanel'>" + ticket.ticket_code + '</div>');

                                }else{

                                    var winnerNo = ticket.ticket_code,
                                    output = [],
                                    sNumber = winnerNo.toString();

                                    for (var isa = 0, len = sNumber.length; isa < len; isa += 1) {
                                        output.push(+sNumber.charAt(isa));
                                    }

                                    var firstDigit = output[0]+1;
                                    var secondDigit = output[1]+1;
                                    var thirdDigit = output[2]+1;
                                    var fourthDigit = output[3]+1;
                                    var fifthDigit = output[4]+1;

                                    // console.log(fifthDigit);
                                    sound.play();

                                    $('#example1 ul').playSpin({
                                        time: 3000,
                                        endNum: [firstDigit, secondDigit, thirdDigit, fourthDigit, fifthDigit],
                                        stopSeq: 'swing',
                                        onEnd: function() {
                                            ding.play(); // Play ding after each number is stopped
                                        },
                                        onFinish: function() {
                                            sound.pause(); // To stop the looping sound is pause it
                                            $("#displayMessage").append("<div class='winnerpanel' id='winnerpanel'> Winner " + ++i + ": " + ticket.ticket_code + '</div>');

                                        }
                                    });

                                    

                                }

                            });
                        

                    },
  
                
        });
    });

**Comment by momokang** [comment]
This is more like logic question instead of this library question, you want to run #example1 twice?
