### ISSUE TITLE
I think a bug

### ISSUE THREAD

**Issue by merdj** [momokang/slotmachine#8]
hi,

i am following your Example 2 - Specify numbers, that will spin and will stop once it reach the specified no. the problem I am encountering is when I have a slot more than 10 putting 0 as the specified value, it does not reach that number instead it will show random number.

![image](https://user-images.githubusercontent.com/1001881/201597891-bc77adab-fd0b-472d-bb68-13b01f3ea7f6.png)

if you put zero as a specific number it will spin but rather than displaying zero it will show different numbers

![image](https://user-images.githubusercontent.com/1001881/201598313-bbf642e0-7db0-4fef-9c31-406a7a0cbb4e.png)

Any workaround for this issue?

thanks

**Comment by momokang** [comment]
I think it's because you didnt declare your number in declaration, your javascript should be something like this:

$('#btn-example2').click(function() {
  var num1 = $('#txt-example2-1').val();
  var num2 = $('#txt-example2-2').val();
  var num3 = $('#txt-example2-3').val();
  var num4 = $('#txt-example2-4').val();
  var num5 = $('#txt-example2-5').val();
  var num6 = $('#txt-example2-6').val();
  var num7 = $('#txt-example2-7').val();
  var num8 = $('#txt-example2-8').val();
  var num9 = $('#txt-example2-9').val();
  var num10 = $('#txt-example2-10').val();
  $('#example2 ul').playSpin({
    endNum: [num1, num2, num3, num4, num5, num6, num7, num8, num9, num10],
  });
});

**Comment by merdj** [comment]
hi,

try it on your side, enter zeroes for the any predefined data and it will not show accurately, it works fine when above zero.

**Comment by momokang** [comment]
What do you mean will not show accurately,

**Comment by merdj** [comment]
![image](https://user-images.githubusercontent.com/1001881/202072129-842d2f39-a9ac-4b04-9c3c-74f3b1032224.png)

from the above sample code which is the example-2 : specifying number"

I entered zeroes to all fields (three zeroes).
I spinned it and the result is wrong. instead of showing three zeroes as selected it selects different numbers.

if enter numbers other than zero it will select the correct entered value.

**Comment by momokang** [comment]
![image](https://user-images.githubusercontent.com/5172626/202074512-822ecbf0-879f-406b-b95d-176c4b79ec04.png)

0 is random, the position is start from 1

**Comment by merdj** [comment]
what if I need a zero value? just like a real life application zero is a number and number zero can be selected as well. What if I bet 100 in a slotmachine, it means I will lose because the system will never select zero. for sure I think it is a bug.

**Comment by momokang** [comment]
The html is like this in example given
<ul>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li class="text-danger">7</li>
  </ul>

if you need 0 number, change your html
<ul>
    <li>0</li>
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5</li>
    <li>6</li>
    <li class="text-danger">7</li>
</ul>

but it will be 1 = 0, 2 = 1

alternatively, add it to 10
<ul>
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5</li>
    <li>6</li>
    <li class="text-danger">7</li>
    <li>8</li>
    <li>9</li>
    <li>0</li>
</ul>

in this example, 10 = 0.
