### ISSUE TITLE
Animaton stacking

### ISSUE THREAD

**Issue by Zaf3487** [momokang/slotmachine#9]
First of all love you're coding approach. The easing bit did the job for me. However I do run into an issue where the animation seems to be stacking and increasing in speed. To counter this I'm look to implement .stop jQuery function but without any luck. Can point me in the right way?

Your coffee is on its way ;)

**Comment by momokang** [comment]
Hello @Zaf3487 , I did figure out the stop time will be increasing if there is a long list of lucky draw, will update it shortly for the fix

**Comment by Zaf3487** [comment]
Great thanks, it is however not so much the stop time. I’m using the manual stop option and everytime I start it again the speed increases. So I want to clear/reset any animation before starting it again

**Comment by momokang** [comment]
Hello @Zaf3487 Checkout the latest commit of stopTime, it will help.

**Comment by momokang** [comment]
$('#example11 ul').playSpin({
    time: $('#txt-example11-time').val(),
    useStopTime: true,
    stopTime: $('#txt-example11-stoptime').val(),
  });

**Comment by Zaf3487** [comment]
Thank you this improves the stopping a lot. I do however still have the issue that if I stop the slotmachine manually and then start it up again it is increasing speed. After 5-8 tries the slotmachine spins out of control. 

I think I found it every time it restarts the cloned LI is added again increasing the overall height and with that the speed. Try1 : 9474 Try2: 10658.25 Try3: 11842.5 Try4: 13026.75 etc.

**Comment by Zaf3487** [comment]
I think i found it. Every time I stop and start the animation slot.listHeight seems to go up. in my case try: 9474 try2: 10658.25 Try3: 11842.5 Try4: 13026.75 etc.

**Comment by momokang** [comment]
Hello @Zaf3487  May I get your start spin options?

**Comment by Zaf3487** [comment]
sure, but as mentioned I'm seeing the cloned li being added everytime I start the spin after stopping it

$(' #slot1').playSpin({
                manualStop: true,
                useStopTime: true,
                endNum: [endNumber[0]],
                onFinish: function (num) {
                    finish1 = 1;
                }
            });

**Comment by momokang** [comment]
Hello, can't replicate your issue, the cloned element will be removed after stop except there is something I had overlooked.

**Comment by Zaf3487** [comment]
Thank you so much your reply let me look into my html code and i used a nested UL inside the slot LI. This caused a child to be hidden. It works now
